// @ts-check
import fs from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// SITE_BASE lets CI build a temporary preview under a sub-path
// (e.g. GitHub Pages) without touching the production config.
const base = process.env.SITE_BASE || '/';
const site = process.env.SITE_URL || 'https://kyber.voget.io';

// Sidebar is generated by scripts/sync-docs.mjs from the kyber repo's
// docs/product/manifest.json (run automatically by the build/dev scripts).
const sidebar = JSON.parse(
	fs.readFileSync(new URL('./src/generated/sidebar.json', import.meta.url), 'utf8'),
);

// https://astro.build/config
export default defineConfig({
	site,
	base,
	integrations: [
		starlight({
			title: 'Kyber',
			description:
				'Run and manage your fleet of AI agents on a Kubernetes cluster. Sandboxed pods, persistent disks, chat from your phone, powered by the subscriptions you already pay for.',
			logo: {
				light: './src/assets/kyber-lockup-light.svg',
				dark: './src/assets/kyber-lockup-dark.svg',
				replacesTitle: true,
			},
			favicon: '/favicon.svg',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/matty-v/kyber' },
			],
			// Per-page editUrl frontmatter (set by sync-docs) points edits at the
			// kyber repo, where the docs actually live.
			customCss: ['./src/styles/custom.css'],
			head: [
				{
					tag: 'meta',
					attrs: { property: 'og:image', content: `${site}/og-image.png` },
				},
				{
					tag: 'meta',
					attrs: { name: 'twitter:card', content: 'summary_large_image' },
				},
			],
			sidebar,
		}),
	],
});
